# Generated by Django 4.1.7 on 2023-04-04 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='first_name',
            new_name='name',
        ),
    ]
