# Generated by Django 4.1.7 on 2023-03-29 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('category', models.CharField(max_length=32)),
                ('brand', models.CharField(max_length=64)),
                ('price', models.FloatField()),
                ('description', models.TextField()),
            ],
        ),
    ]
