# Generated by Django 4.1.7 on 2023-03-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='short_description',
            field=models.CharField(default='НЕТ ОПИСАНИЯ', max_length=128),
        ),
    ]
