# Generated by Django 4.1.7 on 2023-03-31 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_products_short_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
