# Generated by Django 4.2.1 on 2023-05-08 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_products_category_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='category_slug',
            field=models.SlugField(choices=[('shoes', 'shoes'), ('jackets', 'jackets'), ('shirts', 'shirts')], null=True),
        ),
    ]
